-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("Print")
hl.bind("Print", hl.dsp.exec_cmd("dms screenshot full"), { description = "dms screenshot full" })
hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.exec_cmd("dms ipc call lock lock"), { description = "dms ipc call lock lock" })
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.exec_cmd("dms ipc call spotlight toggle"), { description = "dms ipc call spotlight toggle" })
hl.unbind("SUPER + SHIFT + S")
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("dms screenshot"), { description = "dms screenshot" })
hl.unbind("SUPER + A")
hl.bind("SUPER + A", hl.dsp.focus({ workspace = "r-1" }), { description = "Focus Workspace" })
hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.workspace.toggle_special("background"), { description = "Toggle Special Workspace" })
hl.unbind("SUPER + CTRL + Left")
hl.bind("SUPER + CTRL + Left", hl.dsp.focus({ workspace = "r-1" }), { description = "Focus Workspace" })
hl.unbind("SUPER + CTRL + Right")
hl.bind("SUPER + CTRL + Right", hl.dsp.focus({ workspace = "r+1" }), { description = "Focus Workspace" })
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.focus({ workspace = "r+1" }), { description = "Focus Workspace" })
hl.unbind("SUPER + Down")
hl.bind("SUPER + Down", hl.dsp.window.move({ workspace = "special:background", follow = false }), { description = "Move to Workspace (silent)" })
hl.unbind("SUPER + SHIFT + A")
hl.bind("SUPER + SHIFT + A", hl.dsp.window.move({ workspace = "r-1" }), { description = "Move to Workspace" })
hl.unbind("SUPER + SHIFT + B")
hl.bind("SUPER + SHIFT + B", hl.dsp.window.move({ workspace = "special:background" }), { description = "Move to Workspace" })
hl.unbind("SUPER + SHIFT + D")
hl.bind("SUPER + SHIFT + D", hl.dsp.window.move({ workspace = "r+1" }), { description = "Move to Workspace" })
hl.unbind("SUPER + SHIFT + Left")
hl.bind("SUPER + SHIFT + Left", hl.dsp.window.move({ workspace = "r-1" }), { description = "Move to Workspace" })
hl.unbind("SUPER + SHIFT + Right")
hl.bind("SUPER + SHIFT + Right", hl.dsp.window.move({ workspace = "r+1" }), { description = "Move to Workspace" })
hl.unbind("SUPER + mouse_down")
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "r+1" }), { description = "Focus Workspace" })
hl.unbind("SUPER + mouse_up")
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "r-1" }), { description = "Focus Workspace" })
hl.unbind("SUPER + ALT + H")
hl.bind("SUPER + ALT + H", hl.dsp.focus({ monitor = "l" }), { description = "Focus Monitor Left" })
hl.unbind("SUPER + ALT + J")
hl.bind("SUPER + ALT + J", hl.dsp.focus({ monitor = "d" }), { description = "Focus Monitor Down" })
hl.unbind("SUPER + ALT + K")
hl.bind("SUPER + ALT + K", hl.dsp.focus({ monitor = "u" }), { description = "Focus Monitor Up" })
hl.unbind("SUPER + ALT + L")
hl.bind("SUPER + ALT + L", hl.dsp.focus({ monitor = "r" }), { description = "Focus Monitor Right" })
hl.unbind("SUPER + CTRL + H")
hl.bind("SUPER + CTRL + H", hl.dsp.focus({ direction = "l" }), { description = "move focus left" })
hl.unbind("SUPER + CTRL + J")
hl.bind("SUPER + CTRL + J", hl.dsp.focus({ direction = "d" }), { description = "move focus down" })
hl.unbind("SUPER + CTRL + K")
hl.bind("SUPER + CTRL + K", hl.dsp.focus({ direction = "u" }), { description = "move focus up" })
hl.unbind("SUPER + CTRL + L")
hl.bind("SUPER + CTRL + L", hl.dsp.focus({ direction = "r" }), { description = "move focus right" })
hl.unbind("SUPER + Left")
hl.bind("SUPER + Left", hl.dsp.window.move({ direction = "l" }), { description = "move in left direction" })
hl.unbind("SUPER + Right")
hl.bind("SUPER + Right", hl.dsp.window.move({ direction = "r" }), { description = "move in right direction" })
hl.unbind("SUPER + SHIFT + H")
hl.bind("SUPER + SHIFT + H", hl.dsp.window.move({ monitor = "l" }), { description = "Move Window (direction)" })
hl.unbind("SUPER + SHIFT + J")
hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ monitor = "d" }), { description = "Move Window (direction)" })
hl.unbind("SUPER + SHIFT + K")
hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ monitor = "u" }), { description = "Move Window to Monitor" })
hl.unbind("SUPER + SHIFT + L")
hl.bind("SUPER + SHIFT + L", hl.dsp.window.move({ monitor = "r" }), { description = "Move Window (direction)" })
hl.unbind("SUPER + SHIFT + W")
hl.bind("SUPER + SHIFT + W", hl.dsp.window.move({ out_of_group = true }), { description = "Move out of Group" })
hl.unbind("ALT + CTRL + T")
hl.bind("ALT + CTRL + T", hl.dsp.exec_cmd("kitty"), { description = "kitty" })
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("nautilus"))
hl.unbind("SUPER + M")
hl.bind("SUPER + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.unbind("ALT + F4")
hl.bind("ALT + F4", hl.dsp.window.close(), { description = "Close Window (by selector)" })
hl.unbind("ALT + SHIFT + Tab")
hl.bind("ALT + SHIFT + Tab", hl.dsp.group.prev(), { description = "Previous in Group" })
hl.unbind("ALT + Tab")
hl.bind("ALT + Tab", hl.dsp.group.next(), { description = "Next in Group" })
hl.unbind("CTRL + Print")
hl.unbind("SUPER + CTRL + A")
hl.unbind("SUPER + CTRL + B")
hl.unbind("SUPER + CTRL + D")
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.float({ action = "toggle" }), { description = "Float/unfloat window" })
hl.unbind("SUPER + S")
hl.bind("SUPER + S", hl.dsp.layout("togglesplit"), { description = "layoutmsg togglesplit" })
hl.unbind("SUPER + SHIFT + F")
hl.unbind("SUPER + SHIFT + T")
hl.unbind("SUPER + Up")
hl.bind("SUPER + Up", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }), { description = "Toggle Fullscreen" })
hl.unbind("SUPER + space")
