-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("Print")
hl.bind("Print", hl.dsp.exec_cmd("dms screenshot full"), { description = "dms screenshot full" })
hl.unbind("SUPER + CTRL + Q")
hl.bind("SUPER + CTRL + Q", hl.dsp.exec_cmd("dms ipc call lock lock"), { description = "dms ipc call lock lock" })
hl.unbind("SUPER + SHIFT + S")
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("dms screenshot"), { description = "dms screenshot" })
hl.unbind("SUPER + A")
hl.bind("SUPER + A", hl.dsp.focus({ workspace = "r-1" }), { description = "Focus Workspace" })
hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.workspace.toggle_special("background"), { description = "Toggle Special Workspace" })
hl.unbind("SUPER + CTRL + Left")
hl.bind("SUPER + CTRL + Left", hl.dsp.focus({ workspace = "r-1" }), { description = "Focus Workspace" })
hl.unbind("SUPER + CTRL + Right")
hl.bind("SUPER + CTRL + Right", hl.dsp.focus({ workspace = "r+1" }), { description = "Focus Workspace" })
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.focus({ workspace = "r+1" }), { description = "Focus Workspace" })
hl.unbind("SUPER + Down")
hl.bind("SUPER + Down", hl.dsp.window.move({ workspace = "special:background", follow = false }), { description = "Move to Workspace (silent)" })
hl.unbind("SUPER + SHIFT + A")
hl.bind("SUPER + SHIFT + A", hl.dsp.window.move({ workspace = "r-1" }), { description = "Move to Workspace" })
hl.unbind("SUPER + SHIFT + B")
hl.bind("SUPER + SHIFT + B", hl.dsp.window.move({ workspace = "special:background" }), { description = "Move to Workspace" })
hl.unbind("SUPER + SHIFT + D")
hl.bind("SUPER + SHIFT + D", hl.dsp.window.move({ workspace = "r+1" }), { description = "Move to Workspace" })
hl.unbind("SUPER + SHIFT + Left")
hl.bind("SUPER + SHIFT + Left", hl.dsp.window.move({ workspace = "r-1" }), { description = "Move to Workspace" })
hl.unbind("SUPER + SHIFT + Right")
hl.bind("SUPER + SHIFT + Right", hl.dsp.window.move({ workspace = "r+1" }), { description = "Move to Workspace" })
hl.unbind("SUPER + mouse_down")
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "r+1" }), { description = "Focus Workspace" })
hl.unbind("SUPER + mouse_up")
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "r-1" }), { description = "Focus Workspace" })
hl.unbind("SUPER + Left")
hl.bind("SUPER + Left", hl.dsp.window.move({ direction = "l" }), { description = "move in left direction" })
hl.unbind("SUPER + Right")
hl.bind("SUPER + Right", hl.dsp.window.move({ direction = "r" }), { description = "move in right direction" })
hl.unbind("SUPER + SHIFT + W")
hl.bind("SUPER + SHIFT + W", hl.dsp.window.move({ out_of_group = true }), { description = "Move out of Group" })
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("nautilus"))
hl.unbind("SUPER + M")
hl.bind("SUPER + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.unbind("ALT + CTRL + T")
hl.bind("ALT + CTRL + T", hl.dsp.exec_cmd("kitty", {float=true, center=true}), { description = "kitty floating" })
hl.unbind("ALT + F4")
hl.bind("ALT + F4", hl.dsp.window.close(), { description = "Close Window" })
hl.unbind("ALT + SHIFT + Tab")
hl.bind("ALT + SHIFT + Tab", hl.dsp.group.prev(), { description = "Previous in Group" })
hl.unbind("ALT + Tab")
hl.bind("ALT + Tab", hl.dsp.group.next(), { description = "Next in Group" })
hl.unbind("SUPER + S")
hl.bind("SUPER + S", hl.dsp.layout("togglesplit"), { description = "layoutmsg togglesplit" })
hl.unbind("SUPER + Up")
hl.bind("SUPER + Up", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }), { description = "Toggle Fullscreen" })
