-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "eDP-1", mode = "2880x1800@120.001", position = "344x1440", scale = 1.5, vrr = 1, bitdepth = 10, cm = "edid" })
hl.monitor({ output = "DP-3", mode = "3840x2160@60.000", position = "0x0", scale = 1.5, vrr = 0, bitdepth = 10, cm = "dp3" })
