# Mouse mode
set -g mouse on

# Non-login shell
set -g default-command "${SHELL}"

# Vi mode
# 复制模式使用 vim 键位
set -g mode-keys vi
# 命令行（比如 :、命令提示）使用 vim 键位
set -g status-keys vi
# v 开始选择
bind-key -T copy-mode-vi v send -X begin-selection
# y 复制
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
# End of vi mode
