# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix
# End of prefix

# Mouse mode
set -g mouse on

# Non-login shell
set -g default-command "${SHELL}"

# Auto distroy
set -g destroy-unattached on
bind-key P command-prompt -I "#{session_name}" \
  "rename-session '%%'; set-option destroy-unattached off; display-message 'Session is now persistent'"
# End of auto distroy
