# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix
# End of prefix

# Mouse mode
set -g mouse on

# Non-login shell
set -g default-command "${SHELL}"

# Clipboard
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy && wl-paste -n | wl-copy -p"
bind-key p run "wl-paste -n | tmux load-buffer - ; tmux paste-buffer"
# End of clipboard
